### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by escottalexander** [iPaulPro/scaffold-lens#2]
Nice work on this extension. Greatly reduces the complexity of getting set up with testing Lens locally.
I have a suggestion to make it easier for other developers:

Currently in packages/hardhat/config.ts line 16
```
export const BURNER_PUBLIC_KEY = process.env.BURNER_PUBLIC_KEY || "0xCcF81EA786Eb3DfB66EF87862e23D6b1426be65c";
```
I think you should mention this environment variable in your README so that people know they have to change it if they want to add a profile. I would recommend removing your address as the fallback. Is there any drawback to making the fallback be the deployer address?

**Comment by iPaulPro** [comment]
Thanks! I meant to include this in the readme but totally forgot.

I was thinking about just using the deployer key but my main concern was developers accidentally leaking their deployer private key as a public Next.js env variable. When deploying the Lens contracts I must whitelist addresses for them to be able to create profiles, so the corresponding private key is used in the [Nextjs app setup](https://github.com/iPaulPro/scaffold-lens/blob/ee22f9370725a0b93ab680e49a018d6bdc0d0323/extension/packages/nextjs/components/LensProfileProvider.tsx#L6).

I believe using separate burner key variables makes it more clear that this is not a key that should be used in production (or even testnets). Thoughts?

Note that it's not my address, just a random burner wallet key that was created while testing that I decided to use.

**Comment by escottalexander** [comment]
> I believe using separate burner key variables makes it more clear that this is not a key that should be used in production (or even testnets). Thoughts?

In light of the above I think you are probably good to just mention it in the README. Nice work!
